spring.application.name=producto-service
server.port=7073

spring.datasource.url=jdbc:mysql://localhost:3306/bd_producto
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

jwt.secret=mi_clave_super_secreta_1234567890_muy_larga_para_hs256
jwt.expiration-ms=3600000


api.base-url=http://localhost:7070
api.inventario.stock=/inventarios/producto/%d/stock


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html