spring.application.name=compra-service
server.port=7072

spring.datasource.url=jdbc:mysql://localhost:3306/bd_compra
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

jwt.secret=mi_clave_super_secreta_1234567890_muy_larga_para_hs256
jwt.expiration-ms=3600000

api.base-url=http://localhost:7070
api.cliente.exists=/clientes/%d/exists
api.cliente.search=/clientes/search?tipoPiel=%s
api.producto.exists=/productos/%d/exists

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html