spring.application.name=resena-service
server.port=7076

spring.datasource.url=jdbc:mysql://localhost:3306/bd_resena
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
jwt.secret=mi_clave_super_secreta_1234567890_muy_larga_para_hs256
jwt.expiration-ms=3600000
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html